services:

  app:
    image: restuar/macaiki-backend:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      - APP_DEBUG=true
      - APP_SERVER_PORT=8080

      - DB_CONNECTION=MYSQL
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=toor
      - DB_NAME=macaiki
  
  db:
    image: bitnami/mysql
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=macaiki
      - MYSQL_ROOT_PASSWORD=toor
    healthcheck:
      test: ["CMD", "mysql", "-u", "root", "-ptoor", "-e", "show schemas"]
      timeout: 10s